package utkereso.panelek;

/**
 *
 * @author Takacs Peter
 */
public class TervezoPanel extends javax.swing.JPanel {

    
    public TervezoPanel(javax.swing.JPanel megjelenito, javax.swing.JPanel szerkeszto) {
        initComponents();
        Megjelenito.setViewportView(megjelenito);
        Muveletek.setViewportView(szerkeszto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        Muveletek = new javax.swing.JScrollPane();
        Megjelenito = new javax.swing.JScrollPane();

        jSplitPane1.setBorder(null);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setContinuousLayout(true);

        Muveletek.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Muveletek.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Muveletek.setMinimumSize(new java.awt.Dimension(280, 6));
        jSplitPane1.setLeftComponent(Muveletek);

        Megjelenito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jSplitPane1.setRightComponent(Megjelenito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Megjelenito;
    private javax.swing.JScrollPane Muveletek;
    // End of variables declaration//GEN-END:variables
}
